# Choose the cursor for xmonad.
xsetroot -cursor_name left_ptr

xrdb -merge .Xresources

xpmroot ~/pictures/background/14_06_2015.png

setxkbmap gb

# British keyboard layout.
#setxkbmap -layout en-gb

# Lanch xmonad.
exec xmonad
#exec ck-launch-session xmonad




/*xrdb -merge .Xresources*/
/*xpmroot ~/pictures/background/12_05_2015.png*/

/*$HOME/bin/xmodad*/

/*exec xmonad*/
/*[>exec startxfce4<]*/
